version: '3.9'
services:
  redis:
    container_name: redis-dev
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local

